//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNum1.Deploy.Shop.Shop._2014._07._29.shop100000027.Themes.Skin_Default.Skins
{


    public partial class ProductListIsRecommend_two
    {
    }
}
