//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNum1.Deploy.Properties {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "10.0.0.0")]
    internal sealed partial class Settings : global::System.Configuration.ApplicationSettingsBase {
        
        private static Settings defaultInstance = ((Settings)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new Settings())));
        
        public static Settings Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://tj.qq198198.com:88/WebService/City/server.php")]
        public string ShopNum1_Deploy_TJAPI_City {
            get {
                return ((string)(this["ShopNum1_Deploy_TJAPI_City"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://112.124.124.171:8081/WebService.asmx")]
        public string ShopNum1_Deploy_TJAPItwo_P_WebService {
            get {
                return ((string)(this["ShopNum1_Deploy_TJAPItwo_P_WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://112.124.124.171:8081/WebService.asmx")]
        public string ShopNum1_Deploy_TJAPItwo_WebService {
            get {
                return ((string)(this["ShopNum1_Deploy_TJAPItwo_WebService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("http://125.227.91.177:8182/Service/MemberService.asmx")]
        public string ShopNum1_Deploy_TJAPIzhuliang_MemberService {
            get {
                return ((string)(this["ShopNum1_Deploy_TJAPIzhuliang_MemberService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.tj88.com:808/Service/MobileService.asmx")]
        public string ShopNum1_Deploy_comweb_MobileService {
            get {
                return ((string)(this["ShopNum1_Deploy_comweb_MobileService"]));
            }
        }
        
        [global::System.Configuration.ApplicationScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.SpecialSettingAttribute(global::System.Configuration.SpecialSetting.WebServiceUrl)]
        [global::System.Configuration.DefaultSettingValueAttribute("http://www.tj88.com:808/Service/ServiceSlecetOrder.asmx")]
        public string ShopNum1_Deploy_Tj88Rank_ServiceSlecetOrder {
            get {
                return ((string)(this["ShopNum1_Deploy_Tj88Rank_ServiceSlecetOrder"]));
            }
        }
    }
}
