//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace TJAPIzl {
    
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://membersystem.com/", ConfigurationName="TJAPIzl.MemberServiceSoap")]
    public interface MemberServiceSoap {
        
        [System.ServiceModel.OperationContractAttribute(Action="http://membersystem.com/MemberInfo", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MemberInfo(
                    string Number, 
                    string Placement, 
                    string Direct, 
                    string LevelInt, 
                    string Name, 
                    string Sex, 
                    string MobileTele, 
                    string PaperNumber, 
                    string BankName, 
                    string BankAddress, 
                    string BankCard, 
                    string BankBook, 
                    string RegisterDate, 
                    string PetName, 
                    string MemberOrders, 
                    string md5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://membersystem.com/MemberOrder", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MemberOrder(string Number, string Name, string OrderID, string TotalMoney, string TotalPv, string IsAgain, string OrderType, string OrderDate, string md5);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://membersystem.com/MemberOrderBack", ReplyAction="*")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        string MemberOrderBack(string Number, string OrderID, string OrderType, string md5);
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface MemberServiceSoapChannel : TJAPIzl.MemberServiceSoap, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class MemberServiceSoapClient : System.ServiceModel.ClientBase<TJAPIzl.MemberServiceSoap>, TJAPIzl.MemberServiceSoap {
        
        public MemberServiceSoapClient() {
        }
        
        public MemberServiceSoapClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public MemberServiceSoapClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceSoapClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public MemberServiceSoapClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        public string MemberInfo(
                    string Number, 
                    string Placement, 
                    string Direct, 
                    string LevelInt, 
                    string Name, 
                    string Sex, 
                    string MobileTele, 
                    string PaperNumber, 
                    string BankName, 
                    string BankAddress, 
                    string BankCard, 
                    string BankBook, 
                    string RegisterDate, 
                    string PetName, 
                    string MemberOrders, 
                    string md5) {
            return base.Channel.MemberInfo(Number, Placement, Direct, LevelInt, Name, Sex, MobileTele, PaperNumber, BankName, BankAddress, BankCard, BankBook, RegisterDate, PetName, MemberOrders, md5);
        }
        
        public string MemberOrder(string Number, string Name, string OrderID, string TotalMoney, string TotalPv, string IsAgain, string OrderType, string OrderDate, string md5) {
            return base.Channel.MemberOrder(Number, Name, OrderID, TotalMoney, TotalPv, IsAgain, OrderType, OrderDate, md5);
        }
        
        public string MemberOrderBack(string Number, string OrderID, string OrderType, string md5) {
            return base.Channel.MemberOrderBack(Number, OrderID, OrderType, md5);
        }
    }
}
