//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNum1.Deploy.KCELogic {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class CN {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal CN() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopNum1.Deploy.KCELogic.CN", typeof(CN).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 该订单已经支付 的本地化字符串。
        /// </summary>
        internal static string GZ1 {
            get {
                return ResourceManager.GetString("GZ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉,商品太火爆了,库存不足,无法完成下面操作哟！ 的本地化字符串。
        /// </summary>
        internal static string GZ10 {
            get {
                return ResourceManager.GetString("GZ10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买失败 的本地化字符串。
        /// </summary>
        internal static string GZ11 {
            get {
                return ResourceManager.GetString("GZ11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户编号存在，请刷新在次注册 的本地化字符串。
        /// </summary>
        internal static string GZ12 {
            get {
                return ResourceManager.GetString("GZ12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐人不存在 的本地化字符串。
        /// </summary>
        internal static string GZ13 {
            get {
                return ResourceManager.GetString("GZ13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称不能为空 的本地化字符串。
        /// </summary>
        internal static string GZ14 {
            get {
                return ResourceManager.GetString("GZ14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string GZ15 {
            get {
                return ResourceManager.GetString("GZ15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级密码不能为空 的本地化字符串。
        /// </summary>
        internal static string GZ16 {
            get {
                return ResourceManager.GetString("GZ16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐人不存在 的本地化字符串。
        /// </summary>
        internal static string GZ17 {
            get {
                return ResourceManager.GetString("GZ17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册失败!请重新注册! 的本地化字符串。
        /// </summary>
        internal static string GZ18 {
            get {
                return ResourceManager.GetString("GZ18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建ETH地址或NEC地址失败,请重新注册! 的本地化字符串。
        /// </summary>
        internal static string GZ19 {
            get {
                return ResourceManager.GetString("GZ19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付密码为空 的本地化字符串。
        /// </summary>
        internal static string GZ2 {
            get {
                return ResourceManager.GetString("GZ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 对方不是商家,不能转账! 的本地化字符串。
        /// </summary>
        internal static string GZ20 {
            get {
                return ResourceManager.GetString("GZ20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请成功,请耐心等待管理员审批! 的本地化字符串。
        /// </summary>
        internal static string GZ21 {
            get {
                return ResourceManager.GetString("GZ21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已在申请列表中,请耐心等待管理员审批! 的本地化字符串。
        /// </summary>
        internal static string GZ22 {
            get {
                return ResourceManager.GetString("GZ22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有更多商品! 的本地化字符串。
        /// </summary>
        internal static string GZ23 {
            get {
                return ResourceManager.GetString("GZ23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有更多订单! 的本地化字符串。
        /// </summary>
        internal static string GZ24 {
            get {
                return ResourceManager.GetString("GZ24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 起购数量为 的本地化字符串。
        /// </summary>
        internal static string GZ25 {
            get {
                return ResourceManager.GetString("GZ25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 购买数量必须为100的倍数 的本地化字符串。
        /// </summary>
        internal static string GZ26 {
            get {
                return ResourceManager.GetString("GZ26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 库存不足! 的本地化字符串。
        /// </summary>
        internal static string GZ27 {
            get {
                return ResourceManager.GetString("GZ27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您输入的交易密码不正确 的本地化字符串。
        /// </summary>
        internal static string GZ3 {
            get {
                return ResourceManager.GetString("GZ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 付款金额错误 的本地化字符串。
        /// </summary>
        internal static string GZ4 {
            get {
                return ResourceManager.GetString("GZ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您当前帐户上面的NEC不足，无法支付 的本地化字符串。
        /// </summary>
        internal static string GZ5 {
            get {
                return ResourceManager.GetString("GZ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该订单已经支付 的本地化字符串。
        /// </summary>
        internal static string GZ6 {
            get {
                return ResourceManager.GetString("GZ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付失败 的本地化字符串。
        /// </summary>
        internal static string GZ7 {
            get {
                return ResourceManager.GetString("GZ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉,您的租赁算力将超过100万,不可租赁 的本地化字符串。
        /// </summary>
        internal static string GZ8 {
            get {
                return ResourceManager.GetString("GZ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 很抱歉,抢购商品一个ID限购一件！ 的本地化字符串。
        /// </summary>
        internal static string GZ9 {
            get {
                return ResourceManager.GetString("GZ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送成功 的本地化字符串。
        /// </summary>
        internal static string MG000001 {
            get {
                return ResourceManager.GetString("MG000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送成功 的本地化字符串。
        /// </summary>
        internal static string MG0000011 {
            get {
                return ResourceManager.GetString("MG0000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败 的本地化字符串。
        /// </summary>
        internal static string MG000002 {
            get {
                return ResourceManager.GetString("MG000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送失败 的本地化字符串。
        /// </summary>
        internal static string MG0000021 {
            get {
                return ResourceManager.GetString("MG0000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统错误 的本地化字符串。
        /// </summary>
        internal static string MG000003 {
            get {
                return ResourceManager.GetString("MG000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无该UID 的本地化字符串。
        /// </summary>
        internal static string MG000004 {
            get {
                return ResourceManager.GetString("MG000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误 的本地化字符串。
        /// </summary>
        internal static string MG000005 {
            get {
                return ResourceManager.GetString("MG000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 提现金额有误 的本地化字符串。
        /// </summary>
        internal static string MG000006 {
            get {
                return ResourceManager.GetString("MG000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易密码为空! 的本地化字符串。
        /// </summary>
        internal static string MG000007 {
            get {
                return ResourceManager.GetString("MG000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEC不足 的本地化字符串。
        /// </summary>
        internal static string MG000008 {
            get {
                return ResourceManager.GetString("MG000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扣除手续费后不够NEC最低提现额度! 的本地化字符串。
        /// </summary>
        internal static string MG000009 {
            get {
                return ResourceManager.GetString("MG000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易密码错误! 的本地化字符串。
        /// </summary>
        internal static string MG000010 {
            get {
                return ResourceManager.GetString("MG000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 成功! 的本地化字符串。
        /// </summary>
        internal static string MG000011 {
            get {
                return ResourceManager.GetString("MG000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请重新登陆哟，您的身份验证已经过期 的本地化字符串。
        /// </summary>
        internal static string MG000012 {
            get {
                return ResourceManager.GetString("MG000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ETH不足! 的本地化字符串。
        /// </summary>
        internal static string MG000013 {
            get {
                return ResourceManager.GetString("MG000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扣除手续费后不够ETH最低提现额度! 的本地化字符串。
        /// </summary>
        internal static string MG000014 {
            get {
                return ResourceManager.GetString("MG000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 扣除手续费后不够NEC最低提现额度 的本地化字符串。
        /// </summary>
        internal static string MG000015 {
            get {
                return ResourceManager.GetString("MG000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密钥验证失败 的本地化字符串。
        /// </summary>
        internal static string MG000016 {
            get {
                return ResourceManager.GetString("MG000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此账号禁止交易 的本地化字符串。
        /// </summary>
        internal static string MG000017 {
            get {
                return ResourceManager.GetString("MG000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有更多提现记录 的本地化字符串。
        /// </summary>
        internal static string MG000018 {
            get {
                return ResourceManager.GetString("MG000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您不能给自己转账 的本地化字符串。
        /// </summary>
        internal static string MG000019 {
            get {
                return ResourceManager.GetString("MG000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 转账金额有误 的本地化字符串。
        /// </summary>
        internal static string MG000020 {
            get {
                return ResourceManager.GetString("MG000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易密码为空! 的本地化字符串。
        /// </summary>
        internal static string MG000021 {
            get {
                return ResourceManager.GetString("MG000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂时不可互转 的本地化字符串。
        /// </summary>
        internal static string MG000022 {
            get {
                return ResourceManager.GetString("MG000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账号不存在! 的本地化字符串。
        /// </summary>
        internal static string MG000023 {
            get {
                return ResourceManager.GetString("MG000023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USDT不足! 的本地化字符串。
        /// </summary>
        internal static string MG000024 {
            get {
                return ResourceManager.GetString("MG000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ETH地址创建失败 的本地化字符串。
        /// </summary>
        internal static string MG000025 {
            get {
                return ResourceManager.GetString("MG000025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付成功 的本地化字符串。
        /// </summary>
        internal static string MG000026 {
            get {
                return ResourceManager.GetString("MG000026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 参数错误 的本地化字符串。
        /// </summary>
        internal static string MG000027 {
            get {
                return ResourceManager.GetString("MG000027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 没有更多商品 的本地化字符串。
        /// </summary>
        internal static string MG000028 {
            get {
                return ResourceManager.GetString("MG000028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 账户同步成功 的本地化字符串。
        /// </summary>
        internal static string MG000029 {
            get {
                return ResourceManager.GetString("MG000029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改成功 的本地化字符串。
        /// </summary>
        internal static string MG000030 {
            get {
                return ResourceManager.GetString("MG000030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改失败 的本地化字符串。
        /// </summary>
        internal static string MG000031 {
            get {
                return ResourceManager.GetString("MG000031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您不能购买自己的订单! 的本地化字符串。
        /// </summary>
        internal static string MG000032 {
            get {
                return ResourceManager.GetString("MG000032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单状态异常 的本地化字符串。
        /// </summary>
        internal static string MG000033 {
            get {
                return ResourceManager.GetString("MG000033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USDT不足 的本地化字符串。
        /// </summary>
        internal static string MG000034 {
            get {
                return ResourceManager.GetString("MG000034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单不明确 的本地化字符串。
        /// </summary>
        internal static string MG000035 {
            get {
                return ResourceManager.GetString("MG000035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前没有卖单 的本地化字符串。
        /// </summary>
        internal static string MG000036 {
            get {
                return ResourceManager.GetString("MG000036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 目前没有买单 的本地化字符串。
        /// </summary>
        internal static string MG000037 {
            get {
                return ResourceManager.GetString("MG000037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 发送过多 的本地化字符串。
        /// </summary>
        internal static string MG000038 {
            get {
                return ResourceManager.GetString("MG000038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 手机号码已存在 的本地化字符串。
        /// </summary>
        internal static string MG000039 {
            get {
                return ResourceManager.GetString("MG000039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 登陆密码和支付密码不能相等 的本地化字符串。
        /// </summary>
        internal static string MG000040 {
            get {
                return ResourceManager.GetString("MG000040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 交易密码必须为6位 的本地化字符串。
        /// </summary>
        internal static string MG000041 {
            get {
                return ResourceManager.GetString("MG000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 支付密码不能输入非数字 的本地化字符串。
        /// </summary>
        internal static string MG000042 {
            get {
                return ResourceManager.GetString("MG000042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 推荐人不存在 的本地化字符串。
        /// </summary>
        internal static string MG000043 {
            get {
                return ResourceManager.GetString("MG000043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 昵称不能为空 的本地化字符串。
        /// </summary>
        internal static string MG000044 {
            get {
                return ResourceManager.GetString("MG000044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码不能为空 的本地化字符串。
        /// </summary>
        internal static string MG000045 {
            get {
                return ResourceManager.GetString("MG000045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 二级密码不能为空 的本地化字符串。
        /// </summary>
        internal static string MG000046 {
            get {
                return ResourceManager.GetString("MG000046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 注册失败!请重新注册! 的本地化字符串。
        /// </summary>
        internal static string MG000047 {
            get {
                return ResourceManager.GetString("MG000047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 创建ETH地址或NEC地址失败,请重新注册 的本地化字符串。
        /// </summary>
        internal static string MG000048 {
            get {
                return ResourceManager.GetString("MG000048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户已经被禁用 的本地化字符串。
        /// </summary>
        internal static string MG000049 {
            get {
                return ResourceManager.GetString("MG000049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 用户密码错误次数过多已经被禁用 的本地化字符串。
        /// </summary>
        internal static string MG000050 {
            get {
                return ResourceManager.GetString("MG000050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码或者账户可能有误 的本地化字符串。
        /// </summary>
        internal static string MG000051 {
            get {
                return ResourceManager.GetString("MG000051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 两次加密串对比不匹配 的本地化字符串。
        /// </summary>
        internal static string MG000052 {
            get {
                return ResourceManager.GetString("MG000052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 验证码错误，请重新输入验证码 的本地化字符串。
        /// </summary>
        internal static string MG000053 {
            get {
                return ResourceManager.GetString("MG000053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该账号暂无记录 的本地化字符串。
        /// </summary>
        internal static string MG000054 {
            get {
                return ResourceManager.GetString("MG000054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无该手机号 的本地化字符串。
        /// </summary>
        internal static string MG000055 {
            get {
                return ResourceManager.GetString("MG000055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 请联系管理员 的本地化字符串。
        /// </summary>
        internal static string MG000056 {
            get {
                return ResourceManager.GetString("MG000056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您的账户余额不足 的本地化字符串。
        /// </summary>
        internal static string MG000057 {
            get {
                return ResourceManager.GetString("MG000057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 已签到 的本地化字符串。
        /// </summary>
        internal static string MG000058 {
            get {
                return ResourceManager.GetString("MG000058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂无奖金 的本地化字符串。
        /// </summary>
        internal static string MG000059 {
            get {
                return ResourceManager.GetString("MG000059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 未到签到时间 的本地化字符串。
        /// </summary>
        internal static string MG000060 {
            get {
                return ResourceManager.GetString("MG000060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已签到,请勿重复签到 的本地化字符串。
        /// </summary>
        internal static string MG000061 {
            get {
                return ResourceManager.GetString("MG000061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 签到成功 的本地化字符串。
        /// </summary>
        internal static string MG000062 {
            get {
                return ResourceManager.GetString("MG000062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您算力为0,不能签到 的本地化字符串。
        /// </summary>
        internal static string MG000063 {
            get {
                return ResourceManager.GetString("MG000063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 输入他人账号有误 的本地化字符串。
        /// </summary>
        internal static string MG000064 {
            get {
                return ResourceManager.GetString("MG000064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UID和手机号不匹配 的本地化字符串。
        /// </summary>
        internal static string MG000065 {
            get {
                return ResourceManager.GetString("MG000065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改支付密码成功 的本地化字符串。
        /// </summary>
        internal static string MG000066 {
            get {
                return ResourceManager.GetString("MG000066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改登录密码成功 的本地化字符串。
        /// </summary>
        internal static string MG000067 {
            get {
                return ResourceManager.GetString("MG000067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改昵称成功 的本地化字符串。
        /// </summary>
        internal static string MG000068 {
            get {
                return ResourceManager.GetString("MG000068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改昵称失败 的本地化字符串。
        /// </summary>
        internal static string MG000069 {
            get {
                return ResourceManager.GetString("MG000069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 旧密码输入错误 的本地化字符串。
        /// </summary>
        internal static string MG000070 {
            get {
                return ResourceManager.GetString("MG000070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码成功 的本地化字符串。
        /// </summary>
        internal static string MG000071 {
            get {
                return ResourceManager.GetString("MG000071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 修改密码失败 的本地化字符串。
        /// </summary>
        internal static string MG000072 {
            get {
                return ResourceManager.GetString("MG000072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈成功 的本地化字符串。
        /// </summary>
        internal static string MG000073 {
            get {
                return ResourceManager.GetString("MG000073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 反馈失败 的本地化字符串。
        /// </summary>
        internal static string MG000074 {
            get {
                return ResourceManager.GetString("MG000074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已在申请列表中，请等待系统审批！ 的本地化字符串。
        /// </summary>
        internal static string MG000075 {
            get {
                return ResourceManager.GetString("MG000075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定失败,请填写完整信息！ 的本地化字符串。
        /// </summary>
        internal static string MG000076 {
            get {
                return ResourceManager.GetString("MG000076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 您已经绑定过了，请勿重复绑定！ 的本地化字符串。
        /// </summary>
        internal static string MG000077 {
            get {
                return ResourceManager.GetString("MG000077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该设备号已经被绑定！ 的本地化字符串。
        /// </summary>
        internal static string MG000078 {
            get {
                return ResourceManager.GetString("MG000078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 申请绑定失败！ 的本地化字符串。
        /// </summary>
        internal static string MG000079 {
            get {
                return ResourceManager.GetString("MG000079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 系统不存在该设备号！ 的本地化字符串。
        /// </summary>
        internal static string MG000080 {
            get {
                return ResourceManager.GetString("MG000080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 身份验证已过期，请重新登录！ 的本地化字符串。
        /// </summary>
        internal static string MG000081 {
            get {
                return ResourceManager.GetString("MG000081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密钥验证失败！ 的本地化字符串。
        /// </summary>
        internal static string MG000082 {
            get {
                return ResourceManager.GetString("MG000082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 此账号禁止交易 的本地化字符串。
        /// </summary>
        internal static string MG000083 {
            get {
                return ResourceManager.GetString("MG000083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定成功 的本地化字符串。
        /// </summary>
        internal static string MG000084 {
            get {
                return ResourceManager.GetString("MG000084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 绑定失败 的本地化字符串。
        /// </summary>
        internal static string MG000085 {
            get {
                return ResourceManager.GetString("MG000085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 密码输入错误 的本地化字符串。
        /// </summary>
        internal static string MG000086 {
            get {
                return ResourceManager.GetString("MG000086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂时不可挂卖 的本地化字符串。
        /// </summary>
        internal static string MG000087 {
            get {
                return ResourceManager.GetString("MG000087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 暂时不可挂买 的本地化字符串。
        /// </summary>
        internal static string MG000088 {
            get {
                return ResourceManager.GetString("MG000088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 取消订单成功 的本地化字符串。
        /// </summary>
        internal static string MG000089 {
            get {
                return ResourceManager.GetString("MG000089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 该订单已完成交易或订单不存在 的本地化字符串。
        /// </summary>
        internal static string MG000090 {
            get {
                return ResourceManager.GetString("MG000090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 订单不存在 的本地化字符串。
        /// </summary>
        internal static string MG000091 {
            get {
                return ResourceManager.GetString("MG000091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 获取成功 的本地化字符串。
        /// </summary>
        internal static string MG000092 {
            get {
                return ResourceManager.GetString("MG000092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 type不在范围内 的本地化字符串。
        /// </summary>
        internal static string MG000093 {
            get {
                return ResourceManager.GetString("MG000093", resourceCulture);
            }
        }
    }
}
