//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShopNum1.Deploy.KCELogic {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class US {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal US() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ShopNum1.Deploy.KCELogic.US", typeof(US).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 The order has been paid 的本地化字符串。
        /// </summary>
        internal static string GZ1 {
            get {
                return ResourceManager.GetString("GZ1", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sorry, the goods are too hot and the stock is insufficient to complete the following operation yo! 的本地化字符串。
        /// </summary>
        internal static string GZ10 {
            get {
                return ResourceManager.GetString("GZ10", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure to buy 的本地化字符串。
        /// </summary>
        internal static string GZ11 {
            get {
                return ResourceManager.GetString("GZ11", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User number exists, please refresh the registration 的本地化字符串。
        /// </summary>
        internal static string GZ12 {
            get {
                return ResourceManager.GetString("GZ12", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommenders do not exist 的本地化字符串。
        /// </summary>
        internal static string GZ13 {
            get {
                return ResourceManager.GetString("GZ13", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 A nickname cannot be empty 的本地化字符串。
        /// </summary>
        internal static string GZ14 {
            get {
                return ResourceManager.GetString("GZ14", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password cannot be empty 的本地化字符串。
        /// </summary>
        internal static string GZ15 {
            get {
                return ResourceManager.GetString("GZ15", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary password cannot be empty 的本地化字符串。
        /// </summary>
        internal static string GZ16 {
            get {
                return ResourceManager.GetString("GZ16", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Recommenders do not exist 的本地化字符串。
        /// </summary>
        internal static string GZ17 {
            get {
                return ResourceManager.GetString("GZ17", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration failed! Please re-register! 的本地化字符串。
        /// </summary>
        internal static string GZ18 {
            get {
                return ResourceManager.GetString("GZ18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create ETH address or NEC address, please re-register! 的本地化字符串。
        /// </summary>
        internal static string GZ19 {
            get {
                return ResourceManager.GetString("GZ19", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment password is empty 的本地化字符串。
        /// </summary>
        internal static string GZ2 {
            get {
                return ResourceManager.GetString("GZ2", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The other party is not a merchant, can not transfer money! 的本地化字符串。
        /// </summary>
        internal static string GZ20 {
            get {
                return ResourceManager.GetString("GZ20", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful application, please wait patiently for the approval of the administrator! 的本地化字符串。
        /// </summary>
        internal static string GZ21 {
            get {
                return ResourceManager.GetString("GZ21", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already in the application list, please wait patiently for the approval of the administrator! 的本地化字符串。
        /// </summary>
        internal static string GZ22 {
            get {
                return ResourceManager.GetString("GZ22", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more goods! 的本地化字符串。
        /// </summary>
        internal static string GZ23 {
            get {
                return ResourceManager.GetString("GZ23", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more orders! 的本地化字符串。
        /// </summary>
        internal static string GZ24 {
            get {
                return ResourceManager.GetString("GZ24", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The initial purchase quantity is 的本地化字符串。
        /// </summary>
        internal static string GZ25 {
            get {
                return ResourceManager.GetString("GZ25", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Purchase must be multiple of 100 的本地化字符串。
        /// </summary>
        internal static string GZ26 {
            get {
                return ResourceManager.GetString("GZ26", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Insufficient stock! 的本地化字符串。
        /// </summary>
        internal static string GZ27 {
            get {
                return ResourceManager.GetString("GZ27", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transaction password you entered is incorrect 的本地化字符串。
        /// </summary>
        internal static string GZ3 {
            get {
                return ResourceManager.GetString("GZ3", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error in payment amount 的本地化字符串。
        /// </summary>
        internal static string GZ4 {
            get {
                return ResourceManager.GetString("GZ4", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The NEC on your current account is insufficient and cannot be paid. 的本地化字符串。
        /// </summary>
        internal static string GZ5 {
            get {
                return ResourceManager.GetString("GZ5", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order has been paid 的本地化字符串。
        /// </summary>
        internal static string GZ6 {
            get {
                return ResourceManager.GetString("GZ6", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failure to pay 的本地化字符串。
        /// </summary>
        internal static string GZ7 {
            get {
                return ResourceManager.GetString("GZ7", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I&apos;m sorry, but your rental power will exceed 1 million yuan. You can&apos;t rent it. 的本地化字符串。
        /// </summary>
        internal static string GZ8 {
            get {
                return ResourceManager.GetString("GZ8", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 I&apos;m sorry to rush to buy one ID item! 的本地化字符串。
        /// </summary>
        internal static string GZ9 {
            get {
                return ResourceManager.GetString("GZ9", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending successfully 的本地化字符串。
        /// </summary>
        internal static string MG000001 {
            get {
                return ResourceManager.GetString("MG000001", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending successfully 的本地化字符串。
        /// </summary>
        internal static string MG0000011 {
            get {
                return ResourceManager.GetString("MG0000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending successfully 的本地化字符串。
        /// </summary>
        internal static string MG00000111 {
            get {
                return ResourceManager.GetString("MG00000111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending failed 的本地化字符串。
        /// </summary>
        internal static string MG000002 {
            get {
                return ResourceManager.GetString("MG000002", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending failed 的本地化字符串。
        /// </summary>
        internal static string MG0000021 {
            get {
                return ResourceManager.GetString("MG0000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Sending failed 的本地化字符串。
        /// </summary>
        internal static string MG00000211 {
            get {
                return ResourceManager.GetString("MG00000211", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong 的本地化字符串。
        /// </summary>
        internal static string MG000003 {
            get {
                return ResourceManager.GetString("MG000003", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 System Error 的本地化字符串。
        /// </summary>
        internal static string MG0000031 {
            get {
                return ResourceManager.GetString("MG0000031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No UID at present 的本地化字符串。
        /// </summary>
        internal static string MG000004 {
            get {
                return ResourceManager.GetString("MG000004", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No UID at present 的本地化字符串。
        /// </summary>
        internal static string MG0000041 {
            get {
                return ResourceManager.GetString("MG0000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authentication error 的本地化字符串。
        /// </summary>
        internal static string MG000005 {
            get {
                return ResourceManager.GetString("MG000005", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authentication error 的本地化字符串。
        /// </summary>
        internal static string MG0000051 {
            get {
                return ResourceManager.GetString("MG0000051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cash withdrawal was incorrect 的本地化字符串。
        /// </summary>
        internal static string MG000006 {
            get {
                return ResourceManager.GetString("MG000006", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The cash withdrawal was incorrect 的本地化字符串。
        /// </summary>
        internal static string MG0000061 {
            get {
                return ResourceManager.GetString("MG0000061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The trade password is empty 的本地化字符串。
        /// </summary>
        internal static string MG000007 {
            get {
                return ResourceManager.GetString("MG000007", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The trade password is empty 的本地化字符串。
        /// </summary>
        internal static string MG0000071 {
            get {
                return ResourceManager.GetString("MG0000071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEC insufficient 的本地化字符串。
        /// </summary>
        internal static string MG000008 {
            get {
                return ResourceManager.GetString("MG000008", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEC insufficient 的本地化字符串。
        /// </summary>
        internal static string MG0000081 {
            get {
                return ResourceManager.GetString("MG0000081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough after deducting the handling fee NEC minimum cash limit 的本地化字符串。
        /// </summary>
        internal static string MG000009 {
            get {
                return ResourceManager.GetString("MG000009", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough after deducting the handling fee NEC minimum cash limit 的本地化字符串。
        /// </summary>
        internal static string MG0000091 {
            get {
                return ResourceManager.GetString("MG0000091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong trade password 的本地化字符串。
        /// </summary>
        internal static string MG000010 {
            get {
                return ResourceManager.GetString("MG000010", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Wrong trade password 的本地化字符串。
        /// </summary>
        internal static string MG0000101 {
            get {
                return ResourceManager.GetString("MG0000101", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string MG000011 {
            get {
                return ResourceManager.GetString("MG000011", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string MG0000111 {
            get {
                return ResourceManager.GetString("MG0000111", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please login again, your authentication has expired 的本地化字符串。
        /// </summary>
        internal static string MG000012 {
            get {
                return ResourceManager.GetString("MG000012", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please login again, your authentication has expired 的本地化字符串。
        /// </summary>
        internal static string MG0000121 {
            get {
                return ResourceManager.GetString("MG0000121", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ETH is not enough 的本地化字符串。
        /// </summary>
        internal static string MG000013 {
            get {
                return ResourceManager.GetString("MG000013", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 NEC insufficient 的本地化字符串。
        /// </summary>
        internal static string MG0000131 {
            get {
                return ResourceManager.GetString("MG0000131", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough ETH after deducting the handling fee 的本地化字符串。
        /// </summary>
        internal static string MG000014 {
            get {
                return ResourceManager.GetString("MG000014", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not enough ETH after deducting the handling fee 的本地化字符串。
        /// </summary>
        internal static string MG0000141 {
            get {
                return ResourceManager.GetString("MG0000141", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After deducting the handling fee, it is not enough for NEC minimum withdrawal amount 的本地化字符串。
        /// </summary>
        internal static string MG000015 {
            get {
                return ResourceManager.GetString("MG000015", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 After deducting the handling fee, it is not enough for NEC minimum withdrawal amount 的本地化字符串。
        /// </summary>
        internal static string MG0000151 {
            get {
                return ResourceManager.GetString("MG0000151", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key validation failed 的本地化字符串。
        /// </summary>
        internal static string MG000016 {
            get {
                return ResourceManager.GetString("MG000016", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This account prohibits transactions 的本地化字符串。
        /// </summary>
        internal static string MG000017 {
            get {
                return ResourceManager.GetString("MG000017", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more cash withdrawals 的本地化字符串。
        /// </summary>
        internal static string MG000018 {
            get {
                return ResourceManager.GetString("MG000018", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t transfer money to yourself 的本地化字符串。
        /// </summary>
        internal static string MG000019 {
            get {
                return ResourceManager.GetString("MG000019", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transfer amount was incorrect 的本地化字符串。
        /// </summary>
        internal static string MG000020 {
            get {
                return ResourceManager.GetString("MG000020", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The trade password is empty 的本地化字符串。
        /// </summary>
        internal static string MG000021 {
            get {
                return ResourceManager.GetString("MG000021", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not interchangeable for the time being 的本地化字符串。
        /// </summary>
        internal static string MG000022 {
            get {
                return ResourceManager.GetString("MG000022", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Account doesn&apos;t exist 的本地化字符串。
        /// </summary>
        internal static string MG000023 {
            get {
                return ResourceManager.GetString("MG000023", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USDT is not enough 的本地化字符串。
        /// </summary>
        internal static string MG000024 {
            get {
                return ResourceManager.GetString("MG000024", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 ETH address creation failed 的本地化字符串。
        /// </summary>
        internal static string MG000025 {
            get {
                return ResourceManager.GetString("MG000025", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful payment 的本地化字符串。
        /// </summary>
        internal static string MG000026 {
            get {
                return ResourceManager.GetString("MG000026", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Parameter error 的本地化字符串。
        /// </summary>
        internal static string MG000027 {
            get {
                return ResourceManager.GetString("MG000027", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No more merchandise 的本地化字符串。
        /// </summary>
        internal static string MG000028 {
            get {
                return ResourceManager.GetString("MG000028", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Successful account synchronization 的本地化字符串。
        /// </summary>
        internal static string MG000029 {
            get {
                return ResourceManager.GetString("MG000029", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modified successfully 的本地化字符串。
        /// </summary>
        internal static string MG000030 {
            get {
                return ResourceManager.GetString("MG000030", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifications failed 的本地化字符串。
        /// </summary>
        internal static string MG000031 {
            get {
                return ResourceManager.GetString("MG000031", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t buy your own order 的本地化字符串。
        /// </summary>
        internal static string MG000032 {
            get {
                return ResourceManager.GetString("MG000032", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order status exception 的本地化字符串。
        /// </summary>
        internal static string MG000033 {
            get {
                return ResourceManager.GetString("MG000033", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 USDT insufficient 的本地化字符串。
        /// </summary>
        internal static string MG000034 {
            get {
                return ResourceManager.GetString("MG000034", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unclear order 的本地化字符串。
        /// </summary>
        internal static string MG000035 {
            get {
                return ResourceManager.GetString("MG000035", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There&apos;s no bill at the moment 的本地化字符串。
        /// </summary>
        internal static string MG000036 {
            get {
                return ResourceManager.GetString("MG000036", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No bill at the moment 的本地化字符串。
        /// </summary>
        internal static string MG000037 {
            get {
                return ResourceManager.GetString("MG000037", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Send Too Much 的本地化字符串。
        /// </summary>
        internal static string MG000038 {
            get {
                return ResourceManager.GetString("MG000038", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cell phone number already exists 的本地化字符串。
        /// </summary>
        internal static string MG000039 {
            get {
                return ResourceManager.GetString("MG000039", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The login password and the payment password can not be equal 的本地化字符串。
        /// </summary>
        internal static string MG000040 {
            get {
                return ResourceManager.GetString("MG000040", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The transaction password must be 6 bits 的本地化字符串。
        /// </summary>
        internal static string MG000041 {
            get {
                return ResourceManager.GetString("MG000041", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Payment password can not enter non-numbers 的本地化字符串。
        /// </summary>
        internal static string MG000042 {
            get {
                return ResourceManager.GetString("MG000042", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The references don&apos;t exist 的本地化字符串。
        /// </summary>
        internal static string MG000043 {
            get {
                return ResourceManager.GetString("MG000043", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Nicknames can not be empty 的本地化字符串。
        /// </summary>
        internal static string MG000044 {
            get {
                return ResourceManager.GetString("MG000044", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password can not be empty 的本地化字符串。
        /// </summary>
        internal static string MG000045 {
            get {
                return ResourceManager.GetString("MG000045", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Secondary password can not be empty 的本地化字符串。
        /// </summary>
        internal static string MG000046 {
            get {
                return ResourceManager.GetString("MG000046", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Registration failed! Please re-register! 的本地化字符串。
        /// </summary>
        internal static string MG000047 {
            get {
                return ResourceManager.GetString("MG000047", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to create ETH address or NEC address, please re-register 的本地化字符串。
        /// </summary>
        internal static string MG000048 {
            get {
                return ResourceManager.GetString("MG000048", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 User has been disabled 的本地化字符串。
        /// </summary>
        internal static string MG000049 {
            get {
                return ResourceManager.GetString("MG000049", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Too many user password errors have been disabled 的本地化字符串。
        /// </summary>
        internal static string MG000050 {
            get {
                return ResourceManager.GetString("MG000050", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Could be an error in the password or account 的本地化字符串。
        /// </summary>
        internal static string MG000051 {
            get {
                return ResourceManager.GetString("MG000051", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Two matches to the encryption string 的本地化字符串。
        /// </summary>
        internal static string MG000052 {
            get {
                return ResourceManager.GetString("MG000052", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Validator error, please re-enter the validator 的本地化字符串。
        /// </summary>
        internal static string MG000053 {
            get {
                return ResourceManager.GetString("MG000053", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There is no record of the account 的本地化字符串。
        /// </summary>
        internal static string MG000054 {
            get {
                return ResourceManager.GetString("MG000054", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 There&apos;s no cell phone number 的本地化字符串。
        /// </summary>
        internal static string MG000055 {
            get {
                return ResourceManager.GetString("MG000055", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Please contact the administrator 的本地化字符串。
        /// </summary>
        internal static string MG000056 {
            get {
                return ResourceManager.GetString("MG000056", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Your account balance is insufficient 的本地化字符串。
        /// </summary>
        internal static string MG000057 {
            get {
                return ResourceManager.GetString("MG000057", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checked in 的本地化字符串。
        /// </summary>
        internal static string MG000058 {
            get {
                return ResourceManager.GetString("MG000058", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 No bonus at the moment 的本地化字符串。
        /// </summary>
        internal static string MG000059 {
            get {
                return ResourceManager.GetString("MG000059", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Unsigned time 的本地化字符串。
        /// </summary>
        internal static string MG000060 {
            get {
                return ResourceManager.GetString("MG000060", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You have checked in, do not repeat 的本地化字符串。
        /// </summary>
        internal static string MG000061 {
            get {
                return ResourceManager.GetString("MG000061", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Checked in successfully 的本地化字符串。
        /// </summary>
        internal static string MG000062 {
            get {
                return ResourceManager.GetString("MG000062", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You count 0, you can not sign in 的本地化字符串。
        /// </summary>
        internal static string MG000063 {
            get {
                return ResourceManager.GetString("MG000063", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Error entering other person&apos;s account number 的本地化字符串。
        /// </summary>
        internal static string MG000064 {
            get {
                return ResourceManager.GetString("MG000064", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 UID doesn&apos;t match the cell phone number 的本地化字符串。
        /// </summary>
        internal static string MG000065 {
            get {
                return ResourceManager.GetString("MG000065", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifying payment password successful 的本地化字符串。
        /// </summary>
        internal static string MG000066 {
            get {
                return ResourceManager.GetString("MG000066", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifying login password successful 的本地化字符串。
        /// </summary>
        internal static string MG000067 {
            get {
                return ResourceManager.GetString("MG000067", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Modifying nickname successful 的本地化字符串。
        /// </summary>
        internal static string MG000068 {
            get {
                return ResourceManager.GetString("MG000068", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to modify nickname 的本地化字符串。
        /// </summary>
        internal static string MG000069 {
            get {
                return ResourceManager.GetString("MG000069", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Old password input error 的本地化字符串。
        /// </summary>
        internal static string MG000070 {
            get {
                return ResourceManager.GetString("MG000070", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password modification successful 的本地化字符串。
        /// </summary>
        internal static string MG000071 {
            get {
                return ResourceManager.GetString("MG000071", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to change password 的本地化字符串。
        /// </summary>
        internal static string MG000072 {
            get {
                return ResourceManager.GetString("MG000072", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback Success 的本地化字符串。
        /// </summary>
        internal static string MG000073 {
            get {
                return ResourceManager.GetString("MG000073", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Feedback Failed 的本地化字符串。
        /// </summary>
        internal static string MG000074 {
            get {
                return ResourceManager.GetString("MG000074", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already in the application list, please wait for the system approval 的本地化字符串。
        /// </summary>
        internal static string MG000075 {
            get {
                return ResourceManager.GetString("MG000075", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The binding failed, please fill in the full information 的本地化字符串。
        /// </summary>
        internal static string MG000076 {
            get {
                return ResourceManager.GetString("MG000076", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You are already bound, do not repeat the binding 的本地化字符串。
        /// </summary>
        internal static string MG000077 {
            get {
                return ResourceManager.GetString("MG000077", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The device number has been bound 的本地化字符串。
        /// </summary>
        internal static string MG000078 {
            get {
                return ResourceManager.GetString("MG000078", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Failed to apply for binding 的本地化字符串。
        /// </summary>
        internal static string MG000079 {
            get {
                return ResourceManager.GetString("MG000079", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The system does not have the device number 的本地化字符串。
        /// </summary>
        internal static string MG000080 {
            get {
                return ResourceManager.GetString("MG000080", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Authentication has expired, please login again 的本地化字符串。
        /// </summary>
        internal static string MG000081 {
            get {
                return ResourceManager.GetString("MG000081", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Key validation failed 的本地化字符串。
        /// </summary>
        internal static string MG000082 {
            get {
                return ResourceManager.GetString("MG000082", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 This account prohibits transactions 的本地化字符串。
        /// </summary>
        internal static string MG000083 {
            get {
                return ResourceManager.GetString("MG000083", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding successful 的本地化字符串。
        /// </summary>
        internal static string MG000084 {
            get {
                return ResourceManager.GetString("MG000084", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Binding failed 的本地化字符串。
        /// </summary>
        internal static string MG000085 {
            get {
                return ResourceManager.GetString("MG000085", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Password input error 的本地化字符串。
        /// </summary>
        internal static string MG000086 {
            get {
                return ResourceManager.GetString("MG000086", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Not for the time being 的本地化字符串。
        /// </summary>
        internal static string MG000087 {
            get {
                return ResourceManager.GetString("MG000087", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 You can&apos;t hang it for now 的本地化字符串。
        /// </summary>
        internal static string MG000088 {
            get {
                return ResourceManager.GetString("MG000088", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Cancel order successful 的本地化字符串。
        /// </summary>
        internal static string MG000089 {
            get {
                return ResourceManager.GetString("MG000089", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 The order has been completed or the order does not exist 的本地化字符串。
        /// </summary>
        internal static string MG000090 {
            get {
                return ResourceManager.GetString("MG000090", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Order does not exist 的本地化字符串。
        /// </summary>
        internal static string MG000091 {
            get {
                return ResourceManager.GetString("MG000091", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Success 的本地化字符串。
        /// </summary>
        internal static string MG000092 {
            get {
                return ResourceManager.GetString("MG000092", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 Type is out of range 的本地化字符串。
        /// </summary>
        internal static string MG000093 {
            get {
                return ResourceManager.GetString("MG000093", resourceCulture);
            }
        }
    }
}
