//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.1026
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

// 
// 此源代码是由 Microsoft.VSDesigner 4.0.30319.1026 版自动生成。
// 
#pragma warning disable 1591

namespace ShopNum1.Deploy.Tj88Rank {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.ComponentModel;
    using System.Xml.Serialization;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServiceSlecetOrderSoap", Namespace="http://tempuri1.org/")]
    public partial class ServiceSlecetOrder : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback SelecetOrderByTimeOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelecetGoodsByCargthIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelectImgOperationCompleted;
        
        private System.Threading.SendOrPostCallback SelcetOrderByIdOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMenberRankOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMemberSuperiorOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMemberIdentityCardOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMemberNameOperationCompleted;
        
        private System.Threading.SendOrPostCallback Select_Q_S_MemloginIDOperationCompleted;
        
        private System.Threading.SendOrPostCallback UpdateMenberRank_GZOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServiceSlecetOrder() {
            this.Url = global::ShopNum1.Deploy.Properties.Settings.Default.ShopNum1_Deploy_Tj88Rank_ServiceSlecetOrder;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event SelecetOrderByTimeCompletedEventHandler SelecetOrderByTimeCompleted;
        
        /// <remarks/>
        public event SelecetGoodsByCargthIDCompletedEventHandler SelecetGoodsByCargthIDCompleted;
        
        /// <remarks/>
        public event SelectImgCompletedEventHandler SelectImgCompleted;
        
        /// <remarks/>
        public event SelcetOrderByIdCompletedEventHandler SelcetOrderByIdCompleted;
        
        /// <remarks/>
        public event UpdateMenberRankCompletedEventHandler UpdateMenberRankCompleted;
        
        /// <remarks/>
        public event UpdateMemberSuperiorCompletedEventHandler UpdateMemberSuperiorCompleted;
        
        /// <remarks/>
        public event UpdateMemberIdentityCardCompletedEventHandler UpdateMemberIdentityCardCompleted;
        
        /// <remarks/>
        public event UpdateMemberNameCompletedEventHandler UpdateMemberNameCompleted;
        
        /// <remarks/>
        public event Select_Q_S_MemloginIDCompletedEventHandler Select_Q_S_MemloginIDCompleted;
        
        /// <remarks/>
        public event UpdateMenberRank_GZCompletedEventHandler UpdateMenberRank_GZCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/SelecetOrderByTime", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SelecetOrderByTime(string startTime, string orderTime, string cargthid, string md5) {
            object[] results = this.Invoke("SelecetOrderByTime", new object[] {
                        startTime,
                        orderTime,
                        cargthid,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelecetOrderByTimeAsync(string startTime, string orderTime, string cargthid, string md5) {
            this.SelecetOrderByTimeAsync(startTime, orderTime, cargthid, md5, null);
        }
        
        /// <remarks/>
        public void SelecetOrderByTimeAsync(string startTime, string orderTime, string cargthid, string md5, object userState) {
            if ((this.SelecetOrderByTimeOperationCompleted == null)) {
                this.SelecetOrderByTimeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelecetOrderByTimeOperationCompleted);
            }
            this.InvokeAsync("SelecetOrderByTime", new object[] {
                        startTime,
                        orderTime,
                        cargthid,
                        md5}, this.SelecetOrderByTimeOperationCompleted, userState);
        }
        
        private void OnSelecetOrderByTimeOperationCompleted(object arg) {
            if ((this.SelecetOrderByTimeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelecetOrderByTimeCompleted(this, new SelecetOrderByTimeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/SelecetGoodsByCargthID", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SelecetGoodsByCargthID(int startNum, int overNum, string cate_id, string md5) {
            object[] results = this.Invoke("SelecetGoodsByCargthID", new object[] {
                        startNum,
                        overNum,
                        cate_id,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelecetGoodsByCargthIDAsync(int startNum, int overNum, string cate_id, string md5) {
            this.SelecetGoodsByCargthIDAsync(startNum, overNum, cate_id, md5, null);
        }
        
        /// <remarks/>
        public void SelecetGoodsByCargthIDAsync(int startNum, int overNum, string cate_id, string md5, object userState) {
            if ((this.SelecetGoodsByCargthIDOperationCompleted == null)) {
                this.SelecetGoodsByCargthIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelecetGoodsByCargthIDOperationCompleted);
            }
            this.InvokeAsync("SelecetGoodsByCargthID", new object[] {
                        startNum,
                        overNum,
                        cate_id,
                        md5}, this.SelecetGoodsByCargthIDOperationCompleted, userState);
        }
        
        private void OnSelecetGoodsByCargthIDOperationCompleted(object arg) {
            if ((this.SelecetGoodsByCargthIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelecetGoodsByCargthIDCompleted(this, new SelecetGoodsByCargthIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/SelectImg", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SelectImg(int Goos_id, string md5) {
            object[] results = this.Invoke("SelectImg", new object[] {
                        Goos_id,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelectImgAsync(int Goos_id, string md5) {
            this.SelectImgAsync(Goos_id, md5, null);
        }
        
        /// <remarks/>
        public void SelectImgAsync(int Goos_id, string md5, object userState) {
            if ((this.SelectImgOperationCompleted == null)) {
                this.SelectImgOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelectImgOperationCompleted);
            }
            this.InvokeAsync("SelectImg", new object[] {
                        Goos_id,
                        md5}, this.SelectImgOperationCompleted, userState);
        }
        
        private void OnSelectImgOperationCompleted(object arg) {
            if ((this.SelectImgCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelectImgCompleted(this, new SelectImgCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/SelcetOrderById", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string SelcetOrderById(int goosID, string cate_id, string md5) {
            object[] results = this.Invoke("SelcetOrderById", new object[] {
                        goosID,
                        cate_id,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void SelcetOrderByIdAsync(int goosID, string cate_id, string md5) {
            this.SelcetOrderByIdAsync(goosID, cate_id, md5, null);
        }
        
        /// <remarks/>
        public void SelcetOrderByIdAsync(int goosID, string cate_id, string md5, object userState) {
            if ((this.SelcetOrderByIdOperationCompleted == null)) {
                this.SelcetOrderByIdOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelcetOrderByIdOperationCompleted);
            }
            this.InvokeAsync("SelcetOrderById", new object[] {
                        goosID,
                        cate_id,
                        md5}, this.SelcetOrderByIdOperationCompleted, userState);
        }
        
        private void OnSelcetOrderByIdOperationCompleted(object arg) {
            if ((this.SelcetOrderByIdCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.SelcetOrderByIdCompleted(this, new SelcetOrderByIdCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/UpdateMenberRank", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateMenberRank(string rnkGuid, string menberId, string md5) {
            object[] results = this.Invoke("UpdateMenberRank", new object[] {
                        rnkGuid,
                        menberId,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMenberRankAsync(string rnkGuid, string menberId, string md5) {
            this.UpdateMenberRankAsync(rnkGuid, menberId, md5, null);
        }
        
        /// <remarks/>
        public void UpdateMenberRankAsync(string rnkGuid, string menberId, string md5, object userState) {
            if ((this.UpdateMenberRankOperationCompleted == null)) {
                this.UpdateMenberRankOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMenberRankOperationCompleted);
            }
            this.InvokeAsync("UpdateMenberRank", new object[] {
                        rnkGuid,
                        menberId,
                        md5}, this.UpdateMenberRankOperationCompleted, userState);
        }
        
        private void OnUpdateMenberRankOperationCompleted(object arg) {
            if ((this.UpdateMenberRankCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMenberRankCompleted(this, new UpdateMenberRankCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/UpdateMemberSuperior", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateMemberSuperior(string cmember, string memLoginID, string md5) {
            object[] results = this.Invoke("UpdateMemberSuperior", new object[] {
                        cmember,
                        memLoginID,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMemberSuperiorAsync(string cmember, string memLoginID, string md5) {
            this.UpdateMemberSuperiorAsync(cmember, memLoginID, md5, null);
        }
        
        /// <remarks/>
        public void UpdateMemberSuperiorAsync(string cmember, string memLoginID, string md5, object userState) {
            if ((this.UpdateMemberSuperiorOperationCompleted == null)) {
                this.UpdateMemberSuperiorOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMemberSuperiorOperationCompleted);
            }
            this.InvokeAsync("UpdateMemberSuperior", new object[] {
                        cmember,
                        memLoginID,
                        md5}, this.UpdateMemberSuperiorOperationCompleted, userState);
        }
        
        private void OnUpdateMemberSuperiorOperationCompleted(object arg) {
            if ((this.UpdateMemberSuperiorCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMemberSuperiorCompleted(this, new UpdateMemberSuperiorCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/UpdateMemberIdentityCard", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateMemberIdentityCard(string memLoginNO, string IdentityCard, string md5) {
            object[] results = this.Invoke("UpdateMemberIdentityCard", new object[] {
                        memLoginNO,
                        IdentityCard,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMemberIdentityCardAsync(string memLoginNO, string IdentityCard, string md5) {
            this.UpdateMemberIdentityCardAsync(memLoginNO, IdentityCard, md5, null);
        }
        
        /// <remarks/>
        public void UpdateMemberIdentityCardAsync(string memLoginNO, string IdentityCard, string md5, object userState) {
            if ((this.UpdateMemberIdentityCardOperationCompleted == null)) {
                this.UpdateMemberIdentityCardOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMemberIdentityCardOperationCompleted);
            }
            this.InvokeAsync("UpdateMemberIdentityCard", new object[] {
                        memLoginNO,
                        IdentityCard,
                        md5}, this.UpdateMemberIdentityCardOperationCompleted, userState);
        }
        
        private void OnUpdateMemberIdentityCardOperationCompleted(object arg) {
            if ((this.UpdateMemberIdentityCardCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMemberIdentityCardCompleted(this, new UpdateMemberIdentityCardCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/UpdateMemberName", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateMemberName(string name, string memLoginNO, string md5) {
            object[] results = this.Invoke("UpdateMemberName", new object[] {
                        name,
                        memLoginNO,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMemberNameAsync(string name, string memLoginNO, string md5) {
            this.UpdateMemberNameAsync(name, memLoginNO, md5, null);
        }
        
        /// <remarks/>
        public void UpdateMemberNameAsync(string name, string memLoginNO, string md5, object userState) {
            if ((this.UpdateMemberNameOperationCompleted == null)) {
                this.UpdateMemberNameOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMemberNameOperationCompleted);
            }
            this.InvokeAsync("UpdateMemberName", new object[] {
                        name,
                        memLoginNO,
                        md5}, this.UpdateMemberNameOperationCompleted, userState);
        }
        
        private void OnUpdateMemberNameOperationCompleted(object arg) {
            if ((this.UpdateMemberNameCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMemberNameCompleted(this, new UpdateMemberNameCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/Select_Q_S_MemloginID", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string Select_Q_S_MemloginID(string startTime, string orderTime, string md5) {
            object[] results = this.Invoke("Select_Q_S_MemloginID", new object[] {
                        startTime,
                        orderTime,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void Select_Q_S_MemloginIDAsync(string startTime, string orderTime, string md5) {
            this.Select_Q_S_MemloginIDAsync(startTime, orderTime, md5, null);
        }
        
        /// <remarks/>
        public void Select_Q_S_MemloginIDAsync(string startTime, string orderTime, string md5, object userState) {
            if ((this.Select_Q_S_MemloginIDOperationCompleted == null)) {
                this.Select_Q_S_MemloginIDOperationCompleted = new System.Threading.SendOrPostCallback(this.OnSelect_Q_S_MemloginIDOperationCompleted);
            }
            this.InvokeAsync("Select_Q_S_MemloginID", new object[] {
                        startTime,
                        orderTime,
                        md5}, this.Select_Q_S_MemloginIDOperationCompleted, userState);
        }
        
        private void OnSelect_Q_S_MemloginIDOperationCompleted(object arg) {
            if ((this.Select_Q_S_MemloginIDCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.Select_Q_S_MemloginIDCompleted(this, new Select_Q_S_MemloginIDCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapDocumentMethodAttribute("http://tempuri1.org/UpdateMenberRank_GZ", RequestNamespace="http://tempuri1.org/", ResponseNamespace="http://tempuri1.org/", Use=System.Web.Services.Description.SoapBindingUse.Literal, ParameterStyle=System.Web.Services.Protocols.SoapParameterStyle.Wrapped)]
        public string UpdateMenberRank_GZ(string rnkGuid, string menberId, string md5) {
            object[] results = this.Invoke("UpdateMenberRank_GZ", new object[] {
                        rnkGuid,
                        menberId,
                        md5});
            return ((string)(results[0]));
        }
        
        /// <remarks/>
        public void UpdateMenberRank_GZAsync(string rnkGuid, string menberId, string md5) {
            this.UpdateMenberRank_GZAsync(rnkGuid, menberId, md5, null);
        }
        
        /// <remarks/>
        public void UpdateMenberRank_GZAsync(string rnkGuid, string menberId, string md5, object userState) {
            if ((this.UpdateMenberRank_GZOperationCompleted == null)) {
                this.UpdateMenberRank_GZOperationCompleted = new System.Threading.SendOrPostCallback(this.OnUpdateMenberRank_GZOperationCompleted);
            }
            this.InvokeAsync("UpdateMenberRank_GZ", new object[] {
                        rnkGuid,
                        menberId,
                        md5}, this.UpdateMenberRank_GZOperationCompleted, userState);
        }
        
        private void OnUpdateMenberRank_GZOperationCompleted(object arg) {
            if ((this.UpdateMenberRank_GZCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.UpdateMenberRank_GZCompleted(this, new UpdateMenberRank_GZCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SelecetOrderByTimeCompletedEventHandler(object sender, SelecetOrderByTimeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelecetOrderByTimeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelecetOrderByTimeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SelecetGoodsByCargthIDCompletedEventHandler(object sender, SelecetGoodsByCargthIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelecetGoodsByCargthIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelecetGoodsByCargthIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SelectImgCompletedEventHandler(object sender, SelectImgCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelectImgCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelectImgCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void SelcetOrderByIdCompletedEventHandler(object sender, SelcetOrderByIdCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class SelcetOrderByIdCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal SelcetOrderByIdCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateMenberRankCompletedEventHandler(object sender, UpdateMenberRankCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMenberRankCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMenberRankCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateMemberSuperiorCompletedEventHandler(object sender, UpdateMemberSuperiorCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMemberSuperiorCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMemberSuperiorCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateMemberIdentityCardCompletedEventHandler(object sender, UpdateMemberIdentityCardCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMemberIdentityCardCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMemberIdentityCardCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateMemberNameCompletedEventHandler(object sender, UpdateMemberNameCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMemberNameCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMemberNameCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void Select_Q_S_MemloginIDCompletedEventHandler(object sender, Select_Q_S_MemloginIDCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class Select_Q_S_MemloginIDCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal Select_Q_S_MemloginIDCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    public delegate void UpdateMenberRank_GZCompletedEventHandler(object sender, UpdateMenberRank_GZCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.0.30319.1")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class UpdateMenberRank_GZCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal UpdateMenberRank_GZCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public string Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((string)(this.results[0]));
            }
        }
    }
}

#pragma warning restore 1591